spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: 1234
    url: jdbc:mysql://localhost:3306/devrun?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
